#ifndef CONSTS_H
#define CONSTS_H

#include <stdint.h>

#define CHIP8_SCREEN_WIDTH 64
#define CHIP8_SCREEN_HEIGHT 32
#define PIXEL_SCALE_FACTOR 10
#define WINDOW_WIDTH (CHIP8_SCREEN_WIDTH * PIXEL_SCALE_FACTOR)
#define WINDOW_HEIGHT (CHIP8_SCREEN_HEIGHT * PIXEL_SCALE_FACTOR)
#define CPU_CLOCK_DELAY 1 // 1 millisecond.
#define TIMER_CLOCK_DIVISION 9
// Processor's PC starts at 0x200.
#define PROCESSOR_INTERNAL_PROGRAM_COUNTER_START 0x200

#endif
